- name: Ban attacker IP address across servers
  hosts: all
  become: true
  vars:
    attacker_ip: "{{ ip }}"  # 이 값은 --extra-vars로 받음

  tasks:
    - name: Add IP to iptables drop list
      #ansible.builtin.shell: iptables -C INPUT -s {{ attacker_ip }} -j DROP || iptables -A INPUT -s {{ attacker_ip }} -j DROP
      #코드 돌리면 많은 IP가 밴당하기 때문에 테스트 환경에서는 주석처리 할것
      args:
        warn: false
