---
- name: 진단 및 조치 - 접근 IP 및 포트 제한 (TCP Wrappers)
  hosts: target_servers
  become: yes
  gather_facts: yes

  # 1. 변수 정의
  vars:
    # --- 설정 목표 ---
    hosts_deny_file: "/etc/hosts.deny"
    required_deny_rule: "ALL: ALL"
    allow_list_file: "1_1_18_2_allow_list.txt"

    # --- 보고서 관련 ---
    playbook_name: "1_1_18_ip_port_restriction.yml"
    result_json_path: "/tmp/security_report_ip_port_restriction.json"
    remediation_tasks_performed: []

  tasks:
    # 1.5. allow_list 파일 존재 여부 확인 (Control Node에서)
    - name: allow_list 파일 존재 여부 확인
      ansible.builtin.stat:
        path: "{{ allow_list_file }}"
      register: allow_list_stat
      delegate_to: localhost
      become: false

    - name: allow_list 파일 상태 출력
      ansible.builtin.debug:
        msg: |
          파일명: {{ allow_list_file }}
          파일 존재: {{ allow_list_stat.stat.exists }}
          파일 경로: {{ allow_list_stat.stat.path if allow_list_stat.stat.exists else '파일 없음' }}
          파일 크기: {{ allow_list_stat.stat.size if allow_list_stat.stat.exists else 'N/A' }}

    # 1.6. allow_list 파일 내용 미리보기 (파일이 존재할 경우)
    - name: allow_list 파일 내용 미리보기
      ansible.builtin.debug:
        msg: |
          파일 내용:
          {{ lookup('file', allow_list_file).splitlines() }}
      when: allow_list_stat.stat.exists
      delegate_to: localhost

    # 2. 진단
    # /etc/hosts.deny 파일에 'ALL: ALL' 규칙이 있는지 확인
    - name: /etc/hosts.deny 파일의 'ALL ALL' 규칙 존재 여부 진단
      ansible.builtin.shell: "grep -qE '^\\s*ALL\\s*:\\s*ALL\\s*' {{ hosts_deny_file }}"
      register: deny_rule_check
      changed_when: false
      failed_when: false # rc=1 (패턴 없음)은 취약 상태이므로 오류가 아님
      ignore_errors: true # 파일이 없는 경우도 오류가 아님

    # 진단 결과에 따라 취약 여부 변수 설정
    - name: 취약 여부 종합 판단
      ansible.builtin.set_fact:
        # grep 명령어가 실패하면(rc!=0) 'ALL: ALL' 규칙이 없는 것이므로 '취약'
        is_vulnerable: "{{ deny_rule_check.rc != 0 }}"
        report_timestamp: "{{ ansible_date_time.iso8601 }}"

    # 3. 진단 결과 보고
    # 진단 결과를 콘솔에 간단히 출력
    - name: 진단 결과 콘솔 출력
      ansible.builtin.debug:
        msg: "진단결과: {% if is_vulnerable %}취약 (TCP Wrappers의 Default Deny 정책 미설정){% else %}양호{% endif %}"

    # 초기 JSON 보고서 데이터 생성 및 저장
    - name: 초기 JSON 보고서 생성 및 저장
      ansible.builtin.copy:
        content: |
          {{
            {
              "playbook_name": playbook_name,
              "task_description": "접근 IP 및 포트 제한 (TCP Wrappers)",
              "diagnosis_result": "취약" if is_vulnerable else "양호",
              "is_vulnerable": is_vulnerable,
              "timestamp": report_timestamp,
              "hostname": inventory_hostname,
              "allow_list_file_exists": allow_list_stat.stat.exists,
              "vulnerability_details": {
                "reason": "기본 차단 정책인 'ALL: ALL'이 /etc/hosts.deny 파일에 설정되어 있지 않습니다." if is_vulnerable else "/etc/hosts.deny 파일에 기본 차단 정책이 설정되어 있습니다.",
                "recommendation": "/etc/hosts.allow에 허용할 특정 서비스와 IP를 등록하십시오."
              }
            } | to_nice_json
          }}
        dest: "{{ result_json_path }}"
        mode: '0644'
      delegate_to: localhost
      become: false

    # 4. 조치
    # /etc/hosts.deny 파일에 'ALL: ALL' 규칙이 없으면 추가
    - name: /etc/hosts.deny 파일에 ALL ALL 규칙 적용
      ansible.builtin.lineinfile:
        path: "{{ hosts_deny_file }}"
        regexp: '^\s*ALL\s*:\s*ALL'
        line: "{{ required_deny_rule }}"
        state: present
        create: yes
        mode: '0644'
        backup: yes
      register: file_remediation
      when: is_vulnerable

    # 4.5. allow_list 기반 hosts.allow 설정 (파일이 존재할 경우에만)
    - name: 허용 목록 기반으로 /etc/hosts.allow 파일 설정
      ansible.builtin.lineinfile:
        path: /etc/hosts.allow
        line: "sshd: {{ item }}"  # 예시: sshd 서비스에 대해 허용
        state: present
        create: yes
        mode: '0644'
        backup: yes
      loop: "{{ lookup('file', allow_list_file, errors='ignore').splitlines() | default([]) }}"
      when: 
        - is_vulnerable
        - allow_list_stat.stat.exists
        - lookup('file', allow_list_file, errors='ignore') != ""
      register: file_remediation_allow

    # 4.6. allow_list 파일이 없거나 비어있을 경우 기본 설정 적용
    - name: 기본 허용 설정 적용 (allow_list 파일 없음)
      ansible.builtin.lineinfile:
        path: /etc/hosts.allow
        line: "sshd: 127.0.0.1, localhost"  # 기본적으로 로컬호스트만 허용
        state: present
        create: yes
        mode: '0644'
        backup: yes
      when: 
        - is_vulnerable
        - not allow_list_stat.stat.exists
      register: file_remediation_default

    # 4.7. allow_list 파일 상태에 따른 메시지
    - name: allow_list 처리 결과 메시지
      ansible.builtin.debug:
        msg: |
          {% if allow_list_stat.stat.exists %}
          ✅ {{ allow_list_file }} 파일을 사용하여 허용 목록을 설정했습니다.
          {% else %}
          ⚠️ {{ allow_list_file }} 파일이 없어서 기본 설정(localhost만 허용)을 적용했습니다.
          필요시 /etc/hosts.allow 파일을 수동으로 편집하여 허용할 IP를 추가하세요.
          {% endif %}
      when: is_vulnerable

    # 5. 조치 결과 보고
    # 수행된 조치 작업 기록
    - name: 수행된 조치 작업 기록
      ansible.builtin.set_fact:
        remediation_done: "{{ file_remediation.changed | default(false) }}"
        remediation_tasks_performed: "{{ ['/etc/hosts.deny 파일 수정'] if file_remediation.changed | default(false) else [] }}"
        allow_list_applied: "{{ file_remediation_allow.changed | default(false) if allow_list_stat.stat.exists else file_remediation_default.changed | default(false) }}"
        allow_method: "{{ 'custom_list' if allow_list_stat.stat.exists else 'default_localhost' }}"
      when: is_vulnerable

    # 최종 JSON 보고서에 조치 결과 추가 및 저장
    - name: 최종 JSON 보고서에 조치 결과 추가 및 저장
      ansible.builtin.copy:
        content: |
          {{
            (lookup('file', result_json_path) | from_json) | combine({
              'remediation_applied': remediation_done | default(false),
              'remediation_result': '조치 완료' if remediation_done | default(false) else '조치 실패',
              'remediation_timestamp': report_timestamp,
              'remediation_tasks_performed': remediation_tasks_performed | default([]),
              'allow_list_applied': allow_list_applied | default(false),
              'allow_list_file_path': allow_list_file,
              'allow_list_exists': allow_list_stat.stat.exists,
              'allow_method_used': allow_method | default('none')
            }, recursive=True) | to_nice_json
          }}
        dest: "{{ result_json_path }}"
        mode: '0644'
      when: not ansible_check_mode and is_vulnerable
      delegate_to: localhost
      become: false