---
- name: deploy PostTestSite
  hosts: PostWebServers
  become: yes
  vars_files:
    - includes/vault.yml
    - includes/vars.yml
    
  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted
    
    - name: reload apache2
      systemd:
        name: apache2
        state: reloaded

  tasks:
    # 시스템 업데이트
    - name: 시스템 패키지 업데이트
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # PHP 설치 및 설정
    - name: PHP 설치 및 설정
      include_tasks: playbooks/php.yml
      
    # Apache2 설치 및 설정
    - name: Apache2 설치 및 설정
      include_tasks: playbooks/apache.yml

    # MySQL 설치 및 설정  
    - name: MySQL 설치 및 설정
      include_tasks: playbooks/mysql.yml


    # 애플리케이션 배포
    - name: 블로그 애플리케이션 배포
      include_tasks: playbooks/app.yml
