---
- name: Port Scan Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run nmap port scan
      shell:  nmap -p 1-1000 --max-retries 1 -T4 192.168.55.5 -oN ./logs/portscan_result.txt

