- name: SSH Failed Login Simulation from third-party node
  hosts: attacker
  gather_facts: no

  tasks:
    - name: Perform failed ssh attempt with delay
      shell: |
        sshpass -p 'wrongpassword' ssh -o StrictHostKeyChecking=no \
               -o PreferredAuthentications=password -o PubkeyAuthentication=no \
               student2@192.168.55.5 exit || true
      loop: "{{ range(1, 9) | list }}"
      loop_control:
        label: "Try #{{ item }}"
      delay: 5
      ignore_errors: yes

