- name: MySQL 로그 활성화 진단 및 조치
  hosts: target_servers
  become: yes
  gather_facts: yes # OS별 설정 파일 경로를 위해 fact 수집

  # 1. 변수 정의
  vars:
    playbook_name: "mysql_logging_enabled.yml"
    result_json_path: "/tmp/security_report_mysql_logging_enabled.json"
    manual_remediation_guide: "MySQL 설정 파일([mysqld] 섹션)에 'slow_query_log=1'과 'slow_query_log_file=[경로]' 설정을 추가하고 서비스를 재시작하십시오. 필요시 general_log도 활성화할 수 있습니다."
    # OS 계열별 MySQL 설정 파일 경로 정의
    mysql_config_path: "{{ '/etc/my.cnf' if ansible_facts['os_family'] == 'RedHat' else '/etc/mysql/mysql.conf.d/mysqld.cnf' }}"

  tasks:
    # ----------------------------------------------------------------
    # 0. 사전 확인 (MySQL 설치 여부)
    # ----------------------------------------------------------------
    - name: MySQL 설치 여부 확인 (사전 확인)
      ansible.builtin.command: which mysqld
      register: mysql_installed
      changed_when: false
      failed_when: false

    - name: MySQL 미설치 시 작업 종료
      when: mysql_installed.rc != 0
      block:
        - name: MySQL 미설치 메시지 출력
          ansible.builtin.debug:
            msg: "MySQL이 설치되어 있지 않아 진단을 건너뜁니다."
        - name: 플레이북 실행 종료
          ansible.builtin.meta: end_play

    # ----------------------------------------------------------------
    # 2. 진단
    # ----------------------------------------------------------------
    - name: 로그(general_log 또는 slow_query_log) 활성화 여부 진단
      ansible.builtin.shell: "mysql -NBe \"SHOW VARIABLES\" | grep -E '^(general_log|slow_query_log)[[:space:]]' | grep -q 'ON'"
      register: log_status_check
      changed_when: false
      failed_when: false # grep이 ON을 못찾아도(rc=1) 오류가 아님

    - name: 취약 여부 종합 판단
      ansible.builtin.set_fact:
        is_vulnerable: "{{ log_status_check.rc != 0 }}" # grep이 ON을 하나도 못 찾으면(rc=1) 취약
        report_timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: 현재 로그 설정값 확인 (보고서용)
      ansible.builtin.shell: "mysql -NBe \"SHOW VARIABLES WHERE Variable_name IN ('general_log', 'slow_query_log')\""
      register: current_log_status
      changed_when: false

    # ----------------------------------------------------------------
    # 3. 진단 결과 보고
    # ----------------------------------------------------------------
    - name: 진단 결과 콘솔 출력
      ansible.builtin.debug:
        msg: "진단 결과: {% if is_vulnerable %}취약 (general_log와 slow_query_log가 모두 비활성화 상태입니다){% else %}양호{% endif %}"

    - name: 초기 JSON 보고서 생성 및 저장
      ansible.builtin.copy:
        content: |
          {{
            {
              "playbook_name": playbook_name,
              "task_description": "MySQL 로그 활성화 점검",
              "diagnosis_result": "취약" if is_vulnerable else "양호",
              "is_vulnerable": is_vulnerable,
              "timestamp": report_timestamp,
              "hostname": inventory_hostname,
              "vulnerability_details": {
                "reason": "분석에 필요한 로그(general/slow)가 모두 비활성화되어 있습니다." if is_vulnerable else "필수 로그 중 하나 이상이 활성화되어 있습니다.",
                "current_status": current_log_status.stdout_lines | default([])
              },
              "remediation_tasks_performed": []
            } | to_nice_json
          }}
        dest: "{{ result_json_path }}"
        mode: '0644'
      delegate_to: localhost
      become: yes

    # ----------------------------------------------------------------
    # 4. 조치
    # ----------------------------------------------------------------
    - name: 조치 블록 (취약한 경우에만 실행)
      when: is_vulnerable
      block:
        - name: slow_query_log 활성화 설정
          ansible.builtin.lineinfile:
            path: "{{ mysql_config_path }}"
            regexp: '^#?\s*slow_query_log\s*='
            line: 'slow_query_log = 1'
            insertafter: '^\\[mysqld\\]'
            backup: yes
          register: r_slow_log_set
          notify: Restart mysql service

        - name: slow_query_log 파일 경로 설정
          ansible.builtin.lineinfile:
            path: "{{ mysql_config_path }}"
            regexp: '^#?\s*slow_query_log_file\s*='
            line: 'slow_query_log_file = /var/log/mysql/mysql-slow.log'
            insertafter: '^\\[mysqld\\]'
            backup: yes
          register: r_slow_log_file_set
          notify: Restart mysql service

        - name: 핸들러 즉시 실행
          ansible.builtin.meta: flush_handlers

    # ----------------------------------------------------------------
    # 5. 조치 결과 보고
    # ----------------------------------------------------------------
    - name: 수행된 조치 작업 기록
      ansible.builtin.set_fact:
        remediation_done: "{{ (r_slow_log_set is defined and r_slow_log_set.changed) or (r_slow_log_file_set is defined and r_slow_log_file_set.changed) }}"
        remediation_tasks_performed: "{{ (['slow_query_log 활성화'] if r_slow_log_set.changed else []) + (['slow_query_log 파일 경로 설정'] if r_slow_log_file_set.changed else []) }}"
      when: is_vulnerable

    - name: 조치 결과 콘솔 출력
      ansible.builtin.debug:
        msg: |
          총괄 조치 결과: {% if remediation_done | default(false) %}조치 완료 (slow_query_log 활성화)
          {% elif not is_vulnerable %}조치 불필요 (양호)
          {% else %}조치 실패 (수동 조치 필요)
          --------------------------------------------------
          [수동 조치 권고]
          {{ manual_remediation_guide }}
          --------------------------------------------------
          {% endif %}

    - name: 최종 JSON 보고서 파일 덮어쓰기
      ansible.builtin.copy:
        content: |
          {{
            (lookup('file', result_json_path) | from_json) | combine({
              'remediation_applied': remediation_done | default(false),
              'remediation_result': '조치 완료' if (remediation_done | default(false)) else ('조치 불필요' if not is_vulnerable else '조치 실패'),
              'remediation_timestamp': report_timestamp,
              'remediation_tasks_performed': remediation_tasks_performed | default([]),
              'remediation_guide': manual_remediation_guide if (is_vulnerable and not (remediation_done | default(false))) else ''
            }, recursive=True) | to_nice_json
          }}
        dest: "{{ result_json_path }}"
        mode: '0644'
      delegate_to: localhost
      become: yes

  # ----------------------------------------------------------------
  # 핸들러: 조치 시 서비스 재시작
  # ----------------------------------------------------------------
  handlers:
    - name: Restart mysql service
      ansible.builtin.systemd:
        name: "{{ 'mysqld' if ansible_facts['os_family'] == 'RedHat' else 'mysql' }}"
        state: restarted