---
- name: 서버구동 계정 진단
  hosts: PostWebServers
  become: yes

  vars_files:
    - vars.yml
    - vault_vars.yml

  tasks:
    # 1. MySQL 프로세스 실행 계정 확인
    - name: MySQL 프로세스 실행 계정 확인
      shell: ps -ef | grep mysqld | grep -v grep | awk '{print $1}' | head -1
      register: mysql_user
      changed_when: false
      failed_when: false

    # 2. MySQL 설정 파일에서 user 설정 확인
    - name: MySQL 설정 파일 user 설정 확인
      shell: grep "^\s*user\s*=" /etc/mysql/mysql.conf.d/mysqld.cnf | sed 's/.*=\s*//' | tr -d ' ' || echo "설정없음"
      register: config_user
      changed_when: false
      failed_when: false

    # 3. 진단 결과 출력
    - name: MySQL Root 권한 구동 진단 결과
      debug:
        msg: |
          MySQL Root 권한 구동 진단 결과:
          
          프로세스 실행 계정: {{ mysql_user.stdout if mysql_user.stdout else '프로세스 없음' }}
          설정 파일 user 값: {{ config_user.stdout }}
          
          진단 결과: {{ '✅ 양호' if mysql_user.stdout == 'mysql' else '❌ 취약' if mysql_user.stdout == 'root' else '⚠️ 확인 필요' }}
  
    # 4. 취약한 경우 실패 처리
    - name: MySQL Root 권한 구동 취약성 조치
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#\s*user\s*='
        line: 'user = mysql'
        insertafter: '^\[mysqld\]'
      when: mysql_user.stdout == "root"

    - name: MySQL 재시작
      systemd:
        name: mysql
        state: restarted

    # 5. 양호한 경우 성공 메시지
    - name: MySQL Root 권한 구동 양호 확인
      debug:
        msg: "✅ MySQL이 mysql 계정으로 안전하게 구동되고 있습니다."
      when: mysql_user.stdout == "mysql"