---
- name: "inetd/xinetd 설정 파일 권한 관리" # 플레이북 이름
  hosts: localhost # 이 플레이북을 실행할 대상 호스트. 일반적으로 localhost 또는 정의된 그룹
  become: yes # 이 태스크들은 시스템 파일에 접근하므로 sudo 권한이 필요합니다.

  tasks:
    # 1. /etc/inetd.conf 파일의 존재 여부 확인
    - name: "inetd.conf 파일 존재 여부 확인"
      ansible.builtin.stat:
        path: /etc/inetd.conf
      register: stat_inetd_conf # stat 결과를 이 변수에 저장
      changed_when: false # 이 태스크는 파일 시스템을 변경하지 않으므로 변경 없음으로 표시

    # 2. /etc/xinetd.conf 파일의 존재 여부 확인
    - name: "xinetd.conf 파일 존재 여부 확인"
      ansible.builtin.stat:
        path: /etc/xinetd.conf
      register: stat_xinetd_conf # stat 결과를 이 변수에 저장
      changed_when: false # 이 태스크는 파일 시스템을 변경하지 않으므로 변경 없음으로 표시

    # 3. inetd/xinetd 설정 파일의 권한 및 소유자 설정
    # 파일이 존재할 경우에만 해당 태스크를 실행하도록 조건을 추가합니다.
    - name: "inetd/xinetd 설정 파일 권한 설정 (소유자: root, 권한: 644)"
      ansible.builtin.file:
        path: "{{ item }}" # loop 변수인 item을 사용하여 각 파일에 적용
        owner: root # 파일 소유자를 root로 설정
        group: root # 파일 그룹을 root로 설정
        mode: '0644' # 파일 권한을 rw-r--r-- (644)로 설정
        state: file # 파일이 존재함을 보장하고 속성(소유자, 그룹, 권한)을 적용
      loop:
        - /etc/inetd.conf
        - /etc/xinetd.conf
      when: (item == '/etc/inetd.conf' and stat_inetd_conf.stat.exists is defined and stat_inetd_conf.stat.exists) or (item == '/etc/xinetd.conf' and stat_xinetd_conf.stat.exists is defined and stat_xinetd_conf.stat.exists)

