---
- name: World Writable 파일 점검 및 조치
  hosts: localhost # 이 플레이북을 실행할 대상 호스트
  become: yes # 시스템 파일 검색 및 권한 변경을 위해 root 권한이 필요합니다.

  vars:
    # World Writable 파일을 검색할 때 제외할 경로 목록입니다.
    # /tmp는 일반적으로 World Writable 속성을 가지므로 제외합니다.
    excluded_paths_for_find:
      - /proc
      - /sys
      - /dev
      - /run
      - /var/run
      - /var/lock
      - /tmp # /tmp 디렉터리는 일반적으로 World Writable이므로 제외합니다.
      # 추가적으로 World Writable이 의도적으로 설정된 경로가 있다면 여기에 추가하세요.

    # World Writable 권한을 제거할 파일 목록입니다. (조치 시 사용)
    # 기본적으로는 비워둡니다. 여기에 나열된 파일에 대해서만 chmod o-w 명령이 실행됩니다.
    # !! 중요 !!
    # 이 목록에 파일을 추가하기 전에, 해당 파일이 World Writable이 의도된 파일이 아닌지 반드시 확인해야 합니다.
    # 예를 들어, 일부 응용 프로그램은 특정 파일에 대해 World Writable 권한이 필요할 수 있습니다.
    files_to_fix_world_writable: []
      # - /path/to/some/risky_file.txt # 예시: 실제 권한을 변경할 파일의 절대 경로를 여기에 추가하세요.

  tasks:
    - name: "World Writable 파일 검색"
      ansible.builtin.find:
        paths: / # 검색을 시작할 최상위 경로 (루트 디렉터리)
        file_type: file # 검색 대상을 파일로 한정
        mode: '-0002' # World writable 비트(-o 옵션)가 설정된 파일을 찾습니다.
        excludes: "{{ excluded_paths_for_find }}" # 검색에서 제외할 경로 목록
      register: world_writable_files # 발견된 World Writable 파일 목록을 `world_writable_files` 변수에 저장합니다.
      # `can't convert negative value to unsigned int` 경고는 find 모듈 내부에서
      # 특정 파일 시스템이나 메타데이터를 처리할 때 발생할 수 있습니다.
      # 일반적으로 플레이북 실행 자체를 막지는 않지만, 가능한 경우 해당 경로를 `excludes`에 추가하여 회피할 수 있습니다.

    - name: "World Writable 파일 진단 결과 출력"
      ansible.builtin.debug:
        msg: |
          {% if world_writable_files.files | length > 0 %}
            <진단 결과: 취약>
            시스템에 다음 World Writable 파일이 존재합니다.
            세부 정보:
            {% for file in world_writable_files.files %}
              - 경로: {{ file.path }}
                현재 권한 (8진수): {{ file.mode }}
                소유자: {{ file.pw_name | default('알 수 없음') }} (UID: {{ file.uid | default('N/A') }})
                그룹: {{ file.gr_name | default('알 수 없음') }} (GID: {{ file.gid | default('N/A') }})
                수정 시간: {{ file.mtime }} # <-- 시간 필터 없이 Raw 타임스탬프 또는 기본 문자열로 출력
            {% endfor %}
            조치 권고: 위에 나열된 World Writable 파일 중 불필요한 파일의 일반 사용자 쓰기 권한(o-w)을 제거하거나, 파일이 불필요하다면 삭제하십시오.
          {% else %}
            <진단 결과: 양호>
            시스템에서 World Writable 파일을 발견하지 못했습니다. (제외 경로 제외)
          {% endif %}
      when: world_writable_files is defined # 결과가 있을 때만 출력

    - name: "World Writable 권한 제거 (주의 필요!)"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "o-w"
      loop: "{{ files_to_fix_world_writable }}"
      when: files_to_fix_world_writable is defined and files_to_fix_world_writable | length > 0

    - name: "World Writable 권한 제거 후 재확인 메시지"
      ansible.builtin.debug:
        msg: "지정된 파일들의 World Writable 권한 제거를 시도했습니다. 시스템에서 변경사항을 다시 확인해보십시오."
      when: files_to_fix_world_writable is defined and files_to_fix_world_writable | length > 0
