---
- name: "$HOME/.rhosts, hosts.equiv 사용 금지 점검 및 조치"
  hosts: localhost
  become: yes

  vars:
    r_command_files:
      - /etc/hosts.equiv

    excluded_uids:
      - 0
      - 65534

  tasks:
    - name: "시스템의 모든 사용자 정보 가져오기"
      ansible.builtin.command: getent passwd
      register: passwd_output
      changed_when: false

    - name: "일반 사용자 홈 디렉터리 목록 생성"
      ansible.builtin.set_fact:
        users_with_homes: |
          {% set user_list = [] %}
          {% for line in passwd_output.stdout_lines %}
            {% set parts = line.split(':') %}
            {% set username = parts[0] %}
            {% set uid = parts[2] | int %}
            {% set gid = parts[3] | int %}
            {% set home_dir = parts[5] %}
            {% if home_dir and home_dir != '/' and uid >= 1000 and uid not in excluded_uids %}
              {% set _ = user_list.append({'name': username, 'home': home_dir, 'uid': uid, 'gid': gid}) %}
            {% endif %}
          {% endfor %}
          {{ user_list }}
      changed_when: false

    - name: ".rhosts 파일 경로 목록 생성"
      ansible.builtin.set_fact:
        all_r_command_paths: "{{ r_command_files + (users_with_homes | map(attribute='home') | map('regex_replace', '^(.*)$', '\\1/.rhosts') | list) }}"
      changed_when: false

    - name: "각 r-명령 관련 파일의 stat 정보 수집"
      ansible.builtin.stat:
        path: "{{ item }}"
      register: r_command_file_stats
      loop: "{{ all_r_command_paths }}"
      loop_control:
        label: "{{ item }}"

    - name: "취약한 r-명령 관련 파일 목록 초기화"
      ansible.builtin.set_fact:
        vulnerable_r_command_files: []

    - name: "취약한 r-명령 관련 파일 진단 및 목록에 추가"
      ansible.builtin.set_fact:
        vulnerable_r_command_files: "{{ vulnerable_r_command_files + [
          {
            'path': item.stat.path,
            'actual_owner': item.stat.pw_name,
            'actual_mode': item.stat.mode | oct,
            'has_plus_entry': item.content | default('') is search('\\+'),
            'reason': reasons
          }
        ] }}"
      loop: "{{ r_command_file_stats.results }}"
      loop_control:
        label: "{{ item.item }}"
      when:
        - item.stat is defined and item.stat.exists and item.stat.isreg # 파일이 존재하고 일반 파일인 경우
        - > # <-- 이 줄부터 Jinja2 조건이 시작됨을 명시
            ( (item.stat.pw_name != 'root' and (item.item | split('/') | length > 2 and item.stat.pw_name != item.item.split('/')[-2])) or # 소유자 불일치 (.rhosts)
              (item.path == '/etc/hosts.equiv' and item.stat.pw_name != 'root') # /etc/hosts.equiv 소유자 불일치
            ) or
            (item.stat.mode | int > 0o600) or # 권한 600 초과
            (item.content | default('') is search('\\+')) # '+' 설정 존재

      vars: # `reasons` 변수는 `when` 절 아래에 올바르게 들여쓰기 되어야 합니다.
        reasons: |
          {% set current_reasons = [] %}
          {% if item.stat.pw_name != 'root' and (item.item | split('/') | length > 2 and item.stat.pw_name != item.item.split('/')[-2]) %}
            {% set _ = current_reasons.append("소유자가 'root' 또는 해당 계정(" + item.item.split('/')[-2] + ")이 아닙니다. 현재 소유자: " + item.stat.pw_name) %}
          {% elif item.stat.pw_name != 'root' and item.item == '/etc/hosts.equiv' %}
            {% set _ = current_reasons.append("'/etc/hosts.equiv' 파일의 소유자가 'root'가 아닙니다. 현재 소유자: " + item.stat.pw_name) %}
          {% endif %}
          {% if item.stat.mode | int > 0o600 %}
            {% set _ = current_reasons.append("권한이 600(" + (0o600 | oct) + ")을 초과합니다. 현재 권한: " + (item.stat.mode | oct)) %}
          {% endif %}
          {% if item.content | default('') is search('\\+') %}
            {% set _ = current_reasons.append("파일 내용에 위험한 '+' 설정이 포함되어 있습니다.") %}
          {% endif %}
          {{ current_reasons }}

    - name: "R-명령 관련 파일 진단 결과 출력"
      ansible.builtin.debug:
        msg: |
          <진단 결과>
          {% if vulnerable_r_command_files | length > 0 %}
            <취약>
            다음 R-명령 관련 파일들의 보안 설정이 취약합니다:
            {% for file_info in vulnerable_r_command_files %}
              - 파일 경로: {{ file_info.path }}
                실제 소유자: {{ file_info.actual_owner }}
                실제 권한 (8진수): {{ file_info.actual_mode }}
                'plus' 설정 포함 여부: {{ '예' if file_info.has_plus_entry else '아니오' }}
                진단 사유: {{ file_info.reason | join(', ') }}
            {% endfor %}
            조치 권고:
            1. 불필요한 `hosts.equiv` 또는 `.rhosts` 파일은 삭제하십시오.
            2. 파일 사용이 필요한 경우, 소유자를 root 또는 해당 계정으로 변경하고, 권한을 600(-rw-------) 이하로 설정하십시오.
            3. 파일 내용에서 '+' 설정이 있는지 확인하고, 있다면 제거하고 필요한 호스트 및 계정만 명시하십시오.
          {% else %}
            <양호>
            시스템에 취약한 R-명령 관련 파일 설정이 발견되지 않았습니다.
          {% endif %}
      when: r_command_file_stats.results is defined

    # --- 조치: 취약한 R-명령 파일 처리 (주의 필요!) ---
    # 이 조치는 `--check` 옵션 없이 실행될 때만 실제로 적용됩니다.
    # 매우 민감한 파일이므로, 조치 실행 전 반드시 신중하게 검토하고 테스트해야 합니다.

    - name: "위험한 '+' 설정이 있는 .rhosts 및 hosts.equiv 파일 삭제"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ vulnerable_r_command_files }}"
      loop_control:
        label: "삭제 중: {{ item.path }}"
      when:
        - item.has_plus_entry # '+' 설정이 있는 경우에만 삭제
        - ansible_check_mode is not defined # --check 모드가 아닐 때만 실행

    - name: "소유자 및 권한이 부적절한 .rhosts 및 hosts.equiv 파일 수정"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ 'root' if item.path == '/etc/hosts.equiv' else item.path.split('/')[-2] }}"
        group: "{{ 'root' if item.path == '/etc/hosts.equiv' else item.path.split('/')[-2] }}"
        mode: '0600'
      loop: "{{ vulnerable_r_command_files }}"
      loop_control:
        label: "권한/소유자 수정 중: {{ item.path }}"
      when:
        - not item.has_plus_entry # '+' 설정으로 인해 삭제되는 파일은 제외
        - > # <-- 이 줄부터 Jinja2 조건이 시작됨을 명시
            ( (item.actual_owner != 'root' and (item.path != '/etc/hosts.equiv' and item.actual_owner != item.path.split('/')[-2])) or
              (item.path == '/etc/hosts.equiv' and item.actual_owner != 'root') or
              (item.actual_mode | int > 0o600)
            )
        - ansible_check_mode is not defined # --check 모드가 아닐 때만 실행

    - name: "R-명령 관련 파일 조치 후 메시지"
      ansible.builtin.debug:
        msg: "지정된 R-명령 관련 파일들에 대한 조치(삭제 또는 권한/소유자 변경)를 시도했습니다. 시스템에서 변경사항을 다시 확인해보십시오."
      when:
        - vulnerable_r_command_files is defined and vulnerable_r_command_files | length > 0
        - ansible_check_mode is not defined
