---
- name: 진단 및 조치 - root 계정 SSH 원격 접속 제한
  hosts: local
  become: yes
  tasks:
    - name: SSH 설정 파일에서 PermitRootLogin 상태 확인
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+.*'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: SSH 서비스 재시작 (옵션)
      ansible.builtin.service:
        name: ssh
        state: restarted
      tags: restart_ssh
