---
- name: 계정관리 - 패스워드 복잡도 설정 (기존 사용자 제외)
  hosts: local
  become: yes

  vars:
    # 기존 사용자들은 제외하고 새로운 사용자에게만 적용
    # 또는 복잡도 요구사항을 완화
    password_complexity_options: "try_first_pass retry=3 minlen=8 lcredit=-1 dcredit=-1 minclass=2"
    pam_config_file: "/etc/pam.d/common-password"

  tasks:
    - name: pam_pwquality 모듈을 제공하는 패키지 설치
      ansible.builtin.apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: PAM 설정 파일의 pam_pwquality.so 모듈 비밀번호 복잡성 규칙 적용 (완화된 버전)
      ansible.builtin.lineinfile:
        path: "{{ pam_config_file }}"
        regexp: '^#?password\s+(requisite|required)\s+pam_pwquality\.so.*'
        line: "password     requisite       pam_pwquality.so {{ password_complexity_options }}"
        state: present
        backup: yes

    - name: 일반 사용자 계정 목록 가져오기 (shell 명령어 사용)
      ansible.builtin.shell: |
        getent passwd | awk -F: '$3 >= 1000 && $7 !~ /(nologin|false)$/ {print $1}' | tr '\n' ','
      register: user_list_output
      changed_when: false

    - name: 사용자 목록을 리스트로 변환
      set_fact:
        regular_users: "{{ user_list_output.stdout.rstrip(',').split(',') | select('string') | select('ne', '') | list }}"

    - name: 모든 일반 사용자 계정 잠금 해제
      ansible.builtin.command: "faillock --user {{ item }} --reset"
      loop: "{{ regular_users }}"
      ignore_errors: yes
      when: regular_users | length > 0

    - name: 알림 메시지 - 영향받는 사용자 계정 목록
      ansible.builtin.debug:
        msg: |
          ============================================
          보안 설정 적용으로 인한 패스워드 정책 변경 안내
          ============================================
          
          패스워드 복잡도 설정이 완화되었습니다:
          - 최소 길이: 8자 (기존 9자에서 완화)
          - 필수 문자 클래스: 2개 (기존 3개에서 완화)
          
          다음 일반 사용자 계정들의 패스워드를 새로운 요구사항에 맞게 변경해야 합니다:
          {{ regular_users | join(', ') }}
          
          권장 패스워드 형식:
          - 8자 이상
          - 대문자/소문자/숫자/특수문자 중 최소 2가지 조합
          - 예시: Student1, User123!, admin2024 등
          
          모든 계정의 잠금이 해제되었습니다.
          각 계정으로 로그인하여 새로운 요구사항에 맞는 패스워드로 변경하세요.
      when: regular_users | length > 0

    - name: 일반 사용자 계정이 없는 경우 메시지
      ansible.builtin.debug:
        msg: "일반 사용자 계정(UID 1000 이상)이 발견되지 않았습니다."
      when: regular_users | length == 0