---
- name: 서비스 관리 - Finger 서비스 비활성화
  hosts: local
  become: yes

  vars:
    finger_service_name: "finger"
    finger_socket_name: "finger.socket"

  tasks:
    - name: "Finger 서비스 ({{ finger_service_name }}.service) 유닛 파일 존재 여부 확인"
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ finger_service_name }}.service"
      register: finger_service_stat
      when: ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat'

    - name: "Finger 소켓 ({{ finger_socket_name }}) 유닛 파일 존재 여부 확인"
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ finger_socket_name }}"
      register: finger_socket_stat
      when: ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat'

    - name: "/etc/inetd.conf 파일 존재 여부 확인"
      # inetd 기반 시스템에서 finger 서비스 설정을 위한 /etc/inetd.conf 파일 존재 여부를 확인합니다.
      ansible.builtin.stat:
        path: "/etc/inetd.conf"
      register: inetd_conf_stat
      when: ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat'

    - name: "Finger 서비스 비활성화 및 중지 (서비스 유닛 파일이 존재할 경우)"
      ansible.builtin.systemd:
        name: "{{ finger_service_name }}"
        state: stopped
        enabled: no
      when:
        - (ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat')
        - finger_service_stat.stat.exists is defined and finger_service_stat.stat.exists

    - name: "Finger 소켓 비활성화 및 중지 (소켓 유닛 파일이 존재할 경우)"
      ansible.builtin.systemd:
        name: "{{ finger_socket_name }}"
        state: stopped
        enabled: no
      when:
        - (ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat')
        - finger_socket_stat.stat.exists is defined and finger_socket_stat.stat.exists

    - name: "inetd 기반 시스템에서 Finger 서비스 비활성화 (xinetd/inetd 설정)"
      # /etc/inetd.conf 파일이 존재할 경우, "finger" 라인을 주석 처리하여 서비스를 비활성화합니다.
      ansible.builtin.lineinfile:
        path: "/etc/inetd.conf"
        regexp: '^\s*finger\s+'
        line: '#finger'
        state: present
        backup: yes
      when:
        - (ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'RedHat')
        - inetd_conf_stat.stat.exists is defined and inetd_conf_stat.stat.exists # 별도로 등록된 변수 사용
