---
- name: 파일 및 디렉토리 관리 - /etc/passwd 파일 소유자 및 권한 설정
  hosts: local
  become: yes

  tasks:
    - name: "/etc/passwd 파일 소유자 및 권한 설정 (소유자: root, 권한: 644)"
      # /etc/passwd 파일은 사용자 계정 정보를 담고 있으며, 일반 사용자에 의한 변경을 방지하기 위해 권한을 제한합니다.
      # 진단 기준: 양호 - 소유자 root, 권한 644 이하.
      # 조치 방법: 소유자 root, 권한 644로 설정.
      ansible.builtin.file:
        path: "/etc/passwd"
        owner: root
        group: root
        mode: '0644' # 'rw-r--r--'
        state: file
