- name: 계정관리 - 패스워드 복잡도 설정
  hosts: local
  become: yes

  vars:
    # 재시도 기회 : 3, 최소비밀번호 9자, 소문자 최소1개, 숫자 최소1개, 비밀번호에 포함될 최소문자 클래스 수 1개, 비밀번호에 사용자 이름포함금지
    password_complexity_options: "try_first_pass retry=3 minlen=9 lcredit=-1 dcredit=-1 ocredit=-1 minclass=1 reject_username"
    # 주요 PAM 설정 파일 경로 지정
    pam_config_file: "/etc/pam.d/common-password"

  tasks:
    - name: pam_pwquality 모듈을 제공하는 패키지 설치
      ansible.builtin.apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: PAM 설정 파일의 pam_pwquality.so 모듈 비밀번호 복잡성 규칙 적용
      ansible.builtin.lineinfile:
        path: "{{ pam_config_file }}"
        regexp: '^#?password\s+(requisite|required)\s+pam_pwquality\.so.*' # 찾은 라인을 password_complexity_options를 포함하도록 변경합니다.
        line: "password     requisite       pam_pwquality.so {{ password_complexity_options }}"
        state: present # 라인이 없으면 추가하고, 있으면 변경
        backup: yes # 백업 생성
