---
- name: 계정 관리 - root 홈 디렉터리 소유자 설정 및 PATH 환경변수 보안 설정
  hosts: local
  become: yes

  vars:
    # PATH를 검사하고 수정할 root 관련 설정 파일 목록
    # 시스템 환경에 따라 추가/변경될 수 있습니다.
    root_path_config_files:
      - "/etc/profile"
      - "/etc/bash.bashrc"
      - "/root/.bashrc"
      - "/root/.profile"

    # PATH에서 제거할 패턴을 위한 정규표현식
    # 이 정규표현식은 다음과 같은 패턴을 찾아냅니다:
    # 1. ':.': 콜론으로 시작하고 마침표가 붙은 경우 (예: /usr/bin:.:/bin) -> 제거
    # 2. '.:': 마침표로 시작하고 콜론이 붙은 경우 (예: /bin:./sbin) -> 제거
    # 3. '::': 이중 콜론 (빈 경로를 의미) -> 제거
    # 4. ':$': PATH의 끝이 콜론인 경우 -> 제거
    # 5. '^:': PATH의 시작이 콜론인 경우 -> 제거
    # 6. '^\.': PATH의 시작이 마침표인 경우 (예: .:/usr/bin) -> 제거
    path_cleanup_regexp_pattern: '(:|^)\.(:|$)|\:\:|:$|^:'
    # 위 정규표현식은 . 또는 빈 경로를 제거하는 데 사용됩니다.
    # 예: "PATH=/usr/local/bin:.:/usr/bin" -> "PATH=/usr/local/bin:/usr/bin"
    # 예: "PATH=/usr/local/bin::/usr/bin" -> "PATH=/usr/local/bin:/usr/bin"
    # 예: "PATH=:/usr/bin" -> "PATH=/usr/bin"
    # 예: "PATH=/usr/bin:" -> "PATH=/usr/bin"


  tasks:
    - name: "/root 디렉터리 소유자 및 그룹 설정 (소유자: root, 그룹: root)"
      # root 홈 디렉터리(/root)의 소유자가 'root'로 설정되어 있는지 확인하고, 아닐 경우 'root'로 변경합니다.
      # 진단 기준: 양호 - /root 디렉터리의 소유자가 root인 경우.
      # 조치 방법: /root 디렉터리의 소유자를 root로 변경.
      ansible.builtin.file:
        path: "/root"
        owner: root
        group: root
        state: directory # 디렉터리임을 명시
        recurse: no      # 하위 파일 및 디렉터리에는 재귀적으로 적용하지 않음 (이 태스크의 목적은 /root 자체의 소유자 설정이므로)

    - name: "root 계정 PATH 설정 파일에서 '.' 또는 비보안 경로 제거"
      # lineinfile 대신 replace 모듈을 사용하여 파일 내용에서 특정 패턴을 제거합니다.
      # 이 방법이 PATH 환경변수에서 불필요한 요소를 제거하는 데 더 적합합니다.
      ansible.builtin.replace:
        path: "{{ item }}" # 루프 변수를 'item'으로 그대로 사용합니다.
        regexp: "{{ path_cleanup_regexp_pattern }}" # 위에 정의된 정규표현식 사용
        replace: ":" # 일치하는 패턴을 단일 콜론으로 대체하여 경로 구분을 유지 (예: :: -> : )
        backup: yes # 변경 전 원본 파일 백업
      loop: "{{ root_path_config_files }}"
      # loop_control: loop_var: config_file  # 여기서는 필요 없으므로 제거 (기본 item 사용)
      # vars 블록을 특정 태스크에만 적용할 필요가 없습니다. vars 블록은 플레이레벨에 있습니다.

    - name: "경고: PATH에 '.' 또는 비보안 경로가 여전히 남아 있는지 확인 (수동 확인 필요)"
      # 이 태스크는 실제 적용 후 사용자에게 수동 확인을 요청하는 용도입니다.
      # Ansible로 PATH 환경변수를 직접 검사하고 변경하는 것은 복잡하며,
      # 사용자 세션에 따라 다를 수 있으므로, 최종 확인은 수동으로 하는 것이 안전합니다.
      ansible.builtin.shell: |
        echo "현재 root PATH: $(sudo -i sh -c 'echo $PATH')"
        if sudo -i sh -c 'echo $PATH' | grep -Eq '(^:|::$|::|^\.:|:\.:|:\.$)'; then
          echo "경고: root PATH에 여전히 '.' 또는 비보안 경로가 포함되어 있을 수 있습니다."
          echo "다음 파일을 확인하고 수동으로 수정해주세요: {{ root_path_config_files | join(', ') }}"
        else
          echo "root PATH가 양호한 것으로 보입니다."
        fi
      changed_when: false # 변경사항 없음
