---
- name: 계정 관리 - 계정 잠금 임계값 설정 (Ubuntu)
  hosts: local
  become: yes

  vars:
    # 계정 잠금 임계값 설정 (일반적인 보안 권고 기준)
    lockout_threshold: 5     # 실패 시도 횟수 5회
    lockout_time: 300      # 잠금 지속 시간 300초 (5분)

    # Ubuntu의 PAM 설정 파일.
    pam_auth_config: "/etc/pam.d/common-auth"

  tasks:
    - name: "libpam-modules 패키지 설치 확인 (pam_faillock.so 제공)"
      ansible.builtin.apt:
        name: libpam-modules
        state: present
        update_cache: yes

    - name: "{{ pam_auth_config }} 파일의 'auth' 섹션에 pam_faillock.so 'preauth' 라인 추가"
      # pam_unix.so가 실패 시도를 기록하기 전에 pam_faillock.so가 사전 인증 단계에서 동작하도록 설정합니다.
      ansible.builtin.lineinfile:
        path: "{{ pam_auth_config }}"
        regexp: '^auth\s+required\s+pam_faillock\.so\s+preauth.*' # 이미 해당 라인이 있는지 확인
        line: 'auth         required       pam_faillock.so preauth silent audit deny={{ lockout_threshold }} unlock_time={{ lockout_time }}'
        insertbefore: '^auth\s+\\[success=1\s+default=ignore\\]\s+pam_unix\.so.*' # pam_unix.so 라인 이전에 삽입
        state: present
        backup: yes # PAM 파일 수정 시 백업

    - name: "{{ pam_auth_config }} 파일의 'auth' 섹션에 pam_faillock.so 'authfail' 라인 추가"
      # pam_unix.so 이후에 와서 인증 실패 시 계정을 잠급니다.
      ansible.builtin.lineinfile:
        path: "{{ pam_auth_config }}"
        regexp: '^auth\s+\\[default=die\\]\s+pam_faillock\.so\s+authfail.*' # 이미 해당 라인이 있는지 확인
        line: 'auth         [default=die] pam_faillock.so authfail silent audit deny={{ lockout_threshold }} unlock_time={{ lockout_time }}'
        insertafter: '^auth\s+\\[success=1\s+default=ignore\\]\s+pam_unix\.so.*' # pam_unix.so 라인 이후에 삽입
        state: present
        backup: yes # PAM 파일 수정 시 백업

    - name: "{{ pam_auth_config }} 파일의 'account' 섹션에 pam_faillock.so 추가"
      # 계정 스택에 추가하여 성공적인 로그인 시 실패 카운트를 재설정합니다.
      ansible.builtin.lineinfile:
        path: "{{ pam_auth_config }}"
        regexp: '^account\s+required\s+pam_faillock\.so.*' # 이미 해당 라인이 있는지 확인
        line: 'account required       pam_faillock.so'
        insertbefore: '^account\s+required\s+pam_unix\.so.*' # pam_unix.so 라인 이전에 삽입
        state: present
        backup: yes # PAM 파일 수정 시 백업
