---
- name: Restrict access by IP and port
  hosts: all
  become: yes
  vars:
    # 허용할 IP 목록
    allowed_ips:
      - "192.168.0.148"
      - "192.168.0.6"

    # 허용할 포트 (예: SSH 포트)
    allowed_ports:
      - 22

  tasks:

    # TCP Wrappers 설치 (hosts.allow / deny 파일 사용 가능하게 함)
    - name: Install tcpd for TCP Wrappers
      apt:
        name: tcpd
        state: present

    # 모든 접속 거부 설정
    - name: Set ALL:ALL in /etc/hosts.deny
      lineinfile:
        path: /etc/hosts.deny
        line: "ALL:ALL"
        create: yes

    # 허용할 IP만 SSH 접속 허용
    - name: Configure allowed IPs in /etc/hosts.allow for sshd
      copy:
        dest: /etc/hosts.allow
        content: |
          {% for ip in allowed_ips %}
          sshd : {{ ip }}
          {% endfor %}

    # UFW 방화벽 활성화
    - name: Enable UFW firewall
      ufw:
        state: enabled

    # 허용할 IP에 대해 SSH 포트 열기
    - name: Allow SSH from allowed IPs
      ufw:
        rule: allow
        port: "{{ port }}"
        proto: tcp
        from_ip: "{{ ip }}"
      with_nested:
        - "{{ allowed_ports }}"
        - "{{ allowed_ips }}"
      loop_control:
        loop_var: port_ip
      vars:
        port: "{{ port_ip[0] }}"
        ip: "{{ port_ip[1] }}"

    # 기타 IP에 대해 SSH 포트 차단
    - name: Deny SSH from all other IPs
      ufw:
        rule: deny
        port: "{{ item }}"
        proto: tcp
      loop: "{{ allowed_ports }}"
