---
- name: 서비스 관리 - Anonymous FTP 비활성화
  hosts: local
  become: yes

  vars:
    vsftpd_config_path: "/etc/vsftpd.conf"
    vsftpd_config_path_alt: "/etc/vsftpd/vsftpd.conf"
    proftpd_config_path: "/etc/proftpd/proftpd.conf"
    # anonymous 계정으로 사용될 수 있는 사용자 목록
    ftp_users_to_remove:
      - "ftp"
      - "anonymous"

  tasks:
    - name: "vsFTPd 설정 파일 존재 여부 확인"
      # vsFTPd 설정 파일이 시스템에 있는지 확인합니다.
      ansible.builtin.stat:
        path: "{{ item }}"
      register: vsftpd_stat
      loop:
        - "{{ vsftpd_config_path }}"
        - "{{ vsftpd_config_path_alt }}"
      ignore_errors: yes # 파일이 없어도 오류로 처리하지 않음

    - name: "ProFTPD 설정 파일 존재 여부 확인"
      # ProFTPD 설정 파일이 시스템에 있는지 확인합니다.
      ansible.builtin.stat:
        path: "{{ proftpd_config_path }}"
      register: proftpd_stat
      ignore_errors: yes

    - name: "vsFTPd: anonymous_enable=NO 설정"
      # vsFTPd가 설치되어 있고, 설정 파일이 존재하면 anonymous_enable을 NO로 설정합니다.
      # 진단 기준: anonymous_enable = Yes인 경우 취약.
      # 조치 방법: anonymous_enable = NO로 변경.
      ansible.builtin.lineinfile:
        path: "{{ item.item }}"
        regexp: '^anonymous_enable='
        line: "anonymous_enable=NO"
        state: present
        backup: yes
      loop: "{{ vsftpd_stat.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: item.stat.exists is defined and item.stat.exists and item.stat.isfile is defined and item.stat.isfile

    - name: "ProFTPD: UserAlias anonymous ftp 주석 처리"
      # ProFTPD가 설치되어 있고, 설정 파일이 존재하면 UserAlias anonymous ftp 라인을 주석 처리합니다.
      # 진단 기준: UserAlias anonymous ftp가 주석 처리되지 않은 경우 취약.
      # 조치 방법: 해당 라인을 주석 처리.
      ansible.builtin.lineinfile:
        path: "{{ proftpd_config_path }}"
        regexp: '^\s*UserAlias\s+anonymous\s+ftp'
        line: "#UserAlias         anonymous ftp" # 주석 처리된 형태로 변경
        state: present
        backup: yes
      when: proftpd_stat.stat.exists is defined and proftpd_stat.stat.exists and proftpd_stat.stat.isfile is defined and proftpd_stat.stat.isfile

    - name: "일반 FTP: 'ftp' 또는 'anonymous' 계정 삭제"
      # /etc/passwd 파일에 존재할 수 있는 'ftp' 또는 'anonymous' 계정을 삭제합니다.
      # 이는 일반적인 FTP 서비스나 구성에서 익명 접속에 사용될 수 있습니다.
      # 진단 기준: ftp 또는 anonymous 계정이 /etc/passwd에 존재하는 경우 취약.
      # 조치 방법: 해당 계정 삭제.
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent # 계정 삭제
        remove: yes # 홈 디렉토리 및 메일 스풀도 함께 삭제
        force: yes # 강제 삭제 (경고 무시)
      loop: "{{ ftp_users_to_remove }}"
      ignore_errors: yes # 계정이 없어도 오류 발생하지 않도록 설정
      register: userdel_results
      # 이 태스크는 vsftpd/proftpd가 설치되지 않은 경우 또는 일반적인 Anonymous FTP를 고려할 때 실행합니다.
      # 따라서, 특정 FTP 서버에 종속되지 않고 일반적으로 적용할 수 있습니다.

