---
# 플레이북 이름: 불필요한 공유 폴더 제거 점검 및 조치
# 설명: 시스템의 Samba, NFS, 사용자 공유 설정을 진단하고 불필요한 공유 폴더를 제거합니다.
- name: 불필요한 공유 폴더 제거 점검 및 조치
  hosts: localhost
  become: yes

  vars:
    # 공유 서비스 목록
    samba_service_name: smbd
    nfs_service_names: # NFS 서비스 이름은 배포판마다 다를 수 있으므로 여러 이름 시도
      - nfs-kernel-server # Debian/Ubuntu
      - nfs             # RHEL/CentOS/Fedora

    # 설정 파일 경로
    samba_config_file: /etc/samba/smb.conf
    nfs_exports_file: /etc/exports

  tasks:
    # --- 1. 진단 섹션 시작 ---

    - name: 진단 결과 초기화
      ansible.builtin.set_fact:
        diagnosis_results:
          status: "양호"
          reasons: []
          shared_folders_found: false
          needs_fix: false
          details:
            samba_running: false
            nfs_running: false
            usershares_found: false
            smb_conf_shares_found: false
            exports_shares_found: false

    # --- 파일 존재 여부 확인 (stat 모듈 사용 방식 변경) ---
    - name: Samba 설정 파일 (smb.conf) 존재 여부 확인
      ansible.builtin.stat:
        path: "{{ samba_config_file }}"
      register: smb_conf_stat

    - name: NFS exports 파일 (/etc/exports) 존재 여부 확인
      ansible.builtin.stat:
        path: "{{ nfs_exports_file }}"
      register: exports_stat

    # --- 서비스 및 공유 정보 확인 ---
    - name: Samba (smbd) 서비스 실행 여부 확인
      ansible.builtin.shell: "pgrep -f {{ samba_service_name }}"
      register: smbd_process_check
      ignore_errors: true
      changed_when: false

    - name: NFS (nfsd) 서비스 실행 여부 확인
      ansible.builtin.shell: "pgrep -f nfsd"
      register: nfsd_process_check
      ignore_errors: true
      changed_when: false

    - name: 사용자 공유 (net usershare) 존재 여부 확인
      ansible.builtin.shell: "net usershare info --long"
      register: usershare_info
      ignore_errors: true
      changed_when: false

    - name: Samba 설정 파일 (smb.conf) 공유 정의 확인
      ansible.builtin.shell: "grep -E '^\\s*\\[.*\\]' {{ samba_config_file }} | grep -v '^\\[global\\]'"
      register: smb_conf_shares
      ignore_errors: true
      changed_when: false
      when: smb_conf_stat.stat.exists # stat 결과 변수 참조

    - name: NFS exports 파일 (/etc/exports) 공유 정의 확인
      ansible.builtin.shell: "grep -E '^\\s*/' {{ nfs_exports_file }} | grep -v '^\\s*#'"
      register: exports_shares
      ignore_errors: true
      changed_when: false
      when: exports_stat.stat.exists # stat 결과 변수 참조

    # --- 진단 결과 업데이트 ---
    - name: 진단 결과 업데이트 (Samba 서비스 실행 중)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'reasons': diagnosis_results.reasons + ['Samba (smbd) 서비스가 실행 중입니다.'],
              'shared_folders_found': true,
              'needs_fix': true,
              'details': diagnosis_results.details | combine({'samba_running': true})
            })
          }}
      when: smbd_process_check.rc == 0

    - name: 진단 결과 업데이트 (NFS 서비스 실행 중)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'reasons': diagnosis_results.reasons + ['NFS (nfsd) 서비스가 실행 중입니다.'],
              'shared_folders_found': true,
              'needs_fix': true,
              'details': diagnosis_results.details | combine({'nfs_running': true})
            })
          }}
      when: nfsd_process_check.rc == 0

    - name: 진단 결과 업데이트 (사용자 공유 존재)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'reasons': diagnosis_results.reasons + ['`net usershare` 명령으로 설정된 사용자 공유가 존재합니다.'],
              'shared_folders_found': true,
              'needs_fix': true,
              'details': diagnosis_results.details | combine({'usershares_found': true})
            })
          }}
      when: usershare_info.rc is defined and usershare_info.rc == 0 and usershare_info.stdout | trim | length > 0

    - name: 진단 결과 업데이트 (smb.conf에 공유 정의 존재)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'reasons': diagnosis_results.reasons + ['{{ samba_config_file }} 파일에 공유 폴더 정의가 존재합니다.'],
              'shared_folders_found': true,
              'needs_fix': true,
              'details': diagnosis_results.details | combine({'smb_conf_shares_found': true})
            })
          }}
      when: smb_conf_shares.rc is defined and smb_conf_shares.rc == 0 and smb_conf_shares.stdout | trim | length > 0

    - name: 진단 결과 업데이트 (exports 파일에 공유 정의 존재)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'reasons': diagnosis_results.reasons + ['{{ nfs_exports_file }} 파일에 NFS 공유 정의가 존재합니다.'],
              'shared_folders_found': true,
              'needs_fix': true,
              'details': diagnosis_results.details | combine({'exports_shares_found': true})
            })
          }}
      when: exports_shares.rc is defined and exports_shares.rc == 0 and exports_shares.stdout | trim | length > 0


    - name: 최종 진단 결과 출력
      ansible.builtin.debug:
        msg: |
          <진단 결과: {{ diagnosis_results.status }}>
          {% if diagnosis_results.shared_folders_found %}
            시스템에서 공유 폴더 관련 활동/설정이 감지되었습니다:
            {% if diagnosis_results.details.samba_running %}
              - Samba (smbd) 서비스 실행 중
            {% endif %}
            {% if diagnosis_results.details.nfs_running %}
              - NFS (nfsd) 서비스 실행 중
            {% endif %}
            {% if diagnosis_results.details.usershares_found %}
              - 사용자 공유 (net usershare) 설정 존재
            {% endif %}
            {% if diagnosis_results.details.smb_conf_shares_found %}
              - Samba 설정 파일 ({{ samba_config_file }})에 공유 정의 존재
            {% endif %}
            {% if diagnosis_results.details.exports_shares_found %}
              - NFS exports 파일 ({{ nfs_exports_file }})에 공유 정의 존재
            {% endif %}
          {% else %}
            시스템에서 공유 폴더 관련 활동/설정이 감지되지 않았습니다.
          {% endif %}

          {% if diagnosis_results.reasons | length > 0 %}
            세부 사유:
            {% for reason in diagnosis_results.reasons %}
              - {{ reason }}
            {% endfor %}
            조치 권고:
            {% if diagnosis_results.needs_fix %}
              - **필수적이지 않은 경우:** 감지된 공유 서비스(Samba, NFS)를 중지하고 비활성화하십시오.
                - (예시) `sudo systemctl stop smbd` / `sudo systemctl disable smbd`
                - (예시) `sudo systemctl stop nfs-kernel-server` / `sudo systemctl disable nfs-kernel-server`
              - **사용자 공유:** `net usershare`로 설정된 공유가 있다면, `net usershare delete [공유명]` 명령으로 제거하거나 GUI 설정에서 해제하십시오.
              - **설정 파일 내 공유:** `{{ samba_config_file }}` 및 `{{ nfs_exports_file }}` 파일에서 불필요한 공유 정의를 제거하거나, `guest ok = no`와 같이 보안을 강화하십시오.
              - **중요:** 이 조치는 시스템의 공유 기능을 중단시킬 수 있으므로, **반드시 필요한 공유 폴더가 있는지 사전에 확인하십시오.**
            {% else %}
              - 현재 시스템에 불필요한 공유 폴더가 없는 것으로 보입니다.
            {% endif %}
          {% else %}
            현재 시스템에 불필요한 공유 폴더가 없는 것으로 보이며, 보안 설정이 양호합니다.
          {% endif %}
      when: diagnosis_results is defined

    # --- 2. 조치 섹션 시작 (자동 조치) ---
    - name: Samba (smbd) 서비스 중지 및 비활성화
      ansible.builtin.service:
        name: "{{ samba_service_name }}"
        state: stopped
        enabled: no
      when: diagnosis_results.details.samba_running and diagnosis_results.needs_fix
      ignore_errors: true

    - name: NFS 서비스 중지 및 비활성화
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop: "{{ nfs_service_names }}"
      when: diagnosis_results.details.nfs_running and diagnosis_results.needs_fix
      ignore_errors: true

    - name: 사용자 공유 (net usershare) 제거 (감지된 경우)
      ansible.builtin.shell: "net usershare delete '{{ item }}'"
      loop: "{{ usershare_info.stdout_lines | default([]) | map('regex_search', '^\\[(.*)\\]', multiline=True) | select('defined') | map(attribute=1) | list }}"
      when: diagnosis_results.details.usershares_found and diagnosis_results.needs_fix
      ignore_errors: true

    - name: 공유 설정 파일 조치 권고 메시지
      ansible.builtin.debug:
        msg: |
          **주의: Samba 및 NFS 설정 파일 내 공유 정의는 자동으로 제거되지 않습니다.**
          이는 시스템의 정상적인 운영에 영향을 줄 수 있으므로 수동 확인 및 조치가 필요합니다.
          진단 결과에 따라 다음을 확인하십시오:
          - `{{ samba_config_file }}` 파일에서 불필요한 `[공유이름]` 섹션을 제거하거나 `guest ok = no` 설정.
          - `{{ nfs_exports_file }}` 파일에서 불필요한 공유 경로를 제거.
      when: (diagnosis_results.details.smb_conf_shares_found or diagnosis_results.details.exports_shares_found) and diagnosis_results.needs_fix
