---
# 플레이북 이름: 이동식 미디어에 대한 보안 대책 수립 (자동 실행 방지)
# 설명: CD/DVD, USB 등 이동식 미디어 연결 시 자동 실행 기능을 비활성화하여 악성코드 유입을 방지합니다.
# 주의: 이 항목은 주로 GNOME 데스크톱 환경에 해당하며, gsettings 명령에 의존합니다.
- name: 이동식 미디어 자동 실행 방지 설정 점검 및 조치
  hosts: localhost # 로컬 시스템(현재 실행 중인 호스트)을 대상으로 합니다.
  become: no       # 사용자별 GUI 설정이므로 root 권한이 필수는 아닙니다. 사용자 계정으로 실행하는 것이 더 적절할 수 있습니다.

  tasks:
    # --- 1. 진단 섹션 시작 ---

    - name: 진단 결과 초기화
      ansible.builtin.set_fact:
        diagnosis_results:
          status: "진단 불가 (gsettings 부재 또는 GNOME 환경 아님)"
          reasons: []
          needs_fix: false
          gsettings_available: false
          current_autorun_never_setting: "N/A"

    - name: gsettings 명령 존재 여부 확인
      ansible.builtin.command: "which gsettings"
      register: gsettings_path
      changed_when: false
      ignore_errors: true

    - name: gsettings 사용 가능 여부 설정
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'gsettings_available': (gsettings_path.rc == 0)
            }, recursive=True)
          }}

    - name: org.gnome.desktop.media-handling autorun-never 설정 확인
      ansible.builtin.command: gsettings get org.gnome.desktop.media-handling autorun-never
      register: autorun_never_check
      changed_when: false
      ignore_errors: true
      when: diagnosis_results.gsettings_available

    - name: 진단 결과 업데이트 (gsettings 값 기반)
      ansible.builtin.set_fact:
        current_autorun_never_value: "{{ autorun_never_check.stdout | default('false') | trim }}"
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'current_autorun_never_setting': (autorun_never_check.stdout | default('false') | trim) if autorun_never_check.rc == 0 else 'N/A'
            }, recursive=True)
          }}
      when: diagnosis_results.gsettings_available

    - name: 최종 진단 결과 업데이트 (취약 여부 판단)
      ansible.builtin.set_fact:
        diagnosis_results: >-
          {{ diagnosis_results | combine({
              'status': '취약',
              'needs_fix': true,
              'reasons': diagnosis_results.reasons + ['이동식 미디어 자동 실행 방지(`autorun-never`) 설정이 비활성화되어 있습니다. (현재: {{ current_autorun_never_value }})']
            })
          }}
      when:
        - diagnosis_results.gsettings_available
        - current_autorun_never_value != 'true'

    - name: 최종 진단 결과 출력
      ansible.builtin.debug:
        msg: |
          <진단 결과: {{ diagnosis_results.status }}>
          {% if not diagnosis_results.gsettings_available %}
            `gsettings` 명령을 찾을 수 없어 이동식 미디어 자동 실행 설정을 진단할 수 없습니다.
            (GNOME 환경이 아니거나 관련 도구가 설치되지 않은 경우)
          {% else %}
            현재 'autorun-never' 설정: {{ diagnosis_results.current_autorun_never_setting }}
            (권고: true)

            {% if diagnosis_results.needs_fix %}
              세부 사유:
              {% for reason in diagnosis_results.reasons %}
                - {{ reason }}
              {% endfor %}
              조치 권고:
              - **이동식 미디어 자동 실행 기능을 비활성화하십시오.**
              - **자동 조치:** `gsettings set org.gnome.desktop.media-handling autorun-never true`
              - **수동 조치 (GUI):**
                `Settings` → `Removable Media` (또는 `Privacy` → `Removable Media`)로 이동하여
                '미디어가 연결되어도 물어보거나 프로그램 시작하지 않기' 또는 'Never prompt or start programs on media insertion'과 유사한 옵션을 활성화하십시오.
            {% else %}
              이동식 미디어 자동 실행 방지 설정이 양호하게 되어 있습니다.
            {% endif %}
          {% endif %}
      when: diagnosis_results is defined

    # --- 2. 조치 섹션 시작 ---
    # GNOME 환경에서 gsettings를 통해 자동 조치 가능

    - name: 이동식 미디어 자동 실행 방지 설정 적용
      ansible.builtin.command: gsettings set org.gnome.desktop.media-handling autorun-never true
      when:
        - diagnosis_results.needs_fix
        - diagnosis_results.gsettings_available
        - ansible_check_mode is not defined or ansible_check_mode == false
      changed_when: true # 항상 변경된 것으로 간주
