---
- name: PHP 레포지토리 추가
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: PHP 패키지 설치
  apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-bcmath"
      - "libapache2-mod-php{{ php_version }}"
    state: present
    update_cache: yes

- name: PHP 설정 파일 업데이트 (Apache)
  lineinfile:
    path: "/etc/php/{{ php_version }}/apache2/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^upload_max_filesize', line: "upload_max_filesize = 20M" }
    - { regexp: '^post_max_size', line: "post_max_size = 25M" }
    - { regexp: '^max_file_uploads', line: "max_file_uploads = 20" }
    - { regexp: '^memory_limit', line: "memory_limit = 256M" }
    - { regexp: '^max_execution_time', line: "max_execution_time = 120" }
    - { regexp: '^max_input_time', line: "max_input_time = 120" }
  notify: restart apache2

- name: PHP 설정 파일 업데이트 (CLI)
  lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^upload_max_filesize', line: "upload_max_filesize = 20M" }
    - { regexp: '^post_max_size', line: "post_max_size = 25M" }
    - { regexp: '^memory_limit', line: "memory_limit = 256M" }